services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-web-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: app_user
      DB_PASSWORD: password
      DB_NAME: express_db

  db:
    image: postgres:17-alpine
    container_name: express-web-api-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: express_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  seed:
    image: golang:1.26-alpine
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: app_user
      DB_PASSWORD: password
      DB_NAME: express_db
    command: go run ./cmd/seeds

volumes:
  postgres_data: