// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/project.go
//
// Generated by this command:
//
//	mockgen -source=usecase/project.go -destination=usecase/mock_project_repository_test.go -package=usecase ProjectRepository
//

// Package usecase is a generated GoMock package.
package usecase

import (
	ent "0700-express-web-api/ent"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProjectRepository is a mock of ProjectRepository interface.
type MockProjectRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProjectRepositoryMockRecorder
	isgomock struct{}
}

// MockProjectRepositoryMockRecorder is the mock recorder for MockProjectRepository.
type MockProjectRepositoryMockRecorder struct {
	mock *MockProjectRepository
}

// NewMockProjectRepository creates a new mock instance.
func NewMockProjectRepository(ctrl *gomock.Controller) *MockProjectRepository {
	mock := &MockProjectRepository{ctrl: ctrl}
	mock.recorder = &MockProjectRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectRepository) EXPECT() *MockProjectRepositoryMockRecorder {
	return m.recorder
}

// CountProjects mocks base method.
func (m *MockProjectRepository) CountProjects(ctx context.Context, userID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountProjects", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountProjects indicates an expected call of CountProjects.
func (mr *MockProjectRepositoryMockRecorder) CountProjects(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountProjects", reflect.TypeOf((*MockProjectRepository)(nil).CountProjects), ctx, userID)
}

// FindProjectBySlug mocks base method.
func (m *MockProjectRepository) FindProjectBySlug(ctx context.Context, userID, slug string) (*ent.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindProjectBySlug", ctx, userID, slug)
	ret0, _ := ret[0].(*ent.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindProjectBySlug indicates an expected call of FindProjectBySlug.
func (mr *MockProjectRepositoryMockRecorder) FindProjectBySlug(ctx, userID, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindProjectBySlug", reflect.TypeOf((*MockProjectRepository)(nil).FindProjectBySlug), ctx, userID, slug)
}

// FindProjects mocks base method.
func (m *MockProjectRepository) FindProjects(ctx context.Context, userID string, limit, offset int) ([]*ent.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindProjects", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]*ent.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindProjects indicates an expected call of FindProjects.
func (mr *MockProjectRepositoryMockRecorder) FindProjects(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindProjects", reflect.TypeOf((*MockProjectRepository)(nil).FindProjects), ctx, userID, limit, offset)
}
