// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/task.go
//
// Generated by this command:
//
//	mockgen -source=usecase/task.go -destination=usecase/mock_task_repository_test.go -package=usecase TaskRepository
//

// Package usecase is a generated GoMock package.
package usecase

import (
	ent "0700-express-web-api/ent"
	repository "0700-express-web-api/interface/repository"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskRepository is a mock of TaskRepository interface.
type MockTaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRepositoryMockRecorder
	isgomock struct{}
}

// MockTaskRepositoryMockRecorder is the mock recorder for MockTaskRepository.
type MockTaskRepositoryMockRecorder struct {
	mock *MockTaskRepository
}

// NewMockTaskRepository creates a new mock instance.
func NewMockTaskRepository(ctrl *gomock.Controller) *MockTaskRepository {
	mock := &MockTaskRepository{ctrl: ctrl}
	mock.recorder = &MockTaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRepository) EXPECT() *MockTaskRepositoryMockRecorder {
	return m.recorder
}

// CountTasks mocks base method.
func (m *MockTaskRepository) CountTasks(ctx context.Context, userID uuid.UUID, statuses []string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTasks", ctx, userID, statuses)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTasks indicates an expected call of CountTasks.
func (mr *MockTaskRepositoryMockRecorder) CountTasks(ctx, userID, statuses any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTasks", reflect.TypeOf((*MockTaskRepository)(nil).CountTasks), ctx, userID, statuses)
}

// CreateTask mocks base method.
func (m *MockTaskRepository) CreateTask(ctx context.Context, userID uuid.UUID, input repository.CreateTaskInput) (*ent.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", ctx, userID, input)
	ret0, _ := ret[0].(*ent.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockTaskRepositoryMockRecorder) CreateTask(ctx, userID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockTaskRepository)(nil).CreateTask), ctx, userID, input)
}

// DeleteTask mocks base method.
func (m *MockTaskRepository) DeleteTask(ctx context.Context, userID, taskID uuid.UUID) (*ent.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", ctx, userID, taskID)
	ret0, _ := ret[0].(*ent.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockTaskRepositoryMockRecorder) DeleteTask(ctx, userID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockTaskRepository)(nil).DeleteTask), ctx, userID, taskID)
}

// FindTaskByID mocks base method.
func (m *MockTaskRepository) FindTaskByID(ctx context.Context, userID, taskID uuid.UUID) (*ent.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTaskByID", ctx, userID, taskID)
	ret0, _ := ret[0].(*ent.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTaskByID indicates an expected call of FindTaskByID.
func (mr *MockTaskRepositoryMockRecorder) FindTaskByID(ctx, userID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTaskByID", reflect.TypeOf((*MockTaskRepository)(nil).FindTaskByID), ctx, userID, taskID)
}

// FindTasks mocks base method.
func (m *MockTaskRepository) FindTasks(ctx context.Context, userID uuid.UUID, statuses []string, limit, offset int) ([]*ent.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTasks", ctx, userID, statuses, limit, offset)
	ret0, _ := ret[0].([]*ent.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTasks indicates an expected call of FindTasks.
func (mr *MockTaskRepositoryMockRecorder) FindTasks(ctx, userID, statuses, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTasks", reflect.TypeOf((*MockTaskRepository)(nil).FindTasks), ctx, userID, statuses, limit, offset)
}

// UpdateTask mocks base method.
func (m *MockTaskRepository) UpdateTask(ctx context.Context, userID, taskID uuid.UUID, input repository.UpdateTaskInput) (*ent.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", ctx, userID, taskID, input)
	ret0, _ := ret[0].(*ent.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockTaskRepositoryMockRecorder) UpdateTask(ctx, userID, taskID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockTaskRepository)(nil).UpdateTask), ctx, userID, taskID, input)
}
